theme: jekyll-theme-minimal
title: VISAP'18
name: VISAP'18
description: The IEEE VIS 2018 Arts Program, or VISAP’18, showcases innovative artwork and research that explores the exciting and increasingly prominent intersections between art, design, and visualization.
info.date: 23 – 26 October 2018
info.location: Berlin, Germany
twitter:
  username: ieeevisap
logo: /media/visap18-teaser.jpg
default:
  -
    scope:
      path: ""
      type: "posts"
    values:
      image: /media/visap18-teaser.jpg
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /media/visap18-teaser.jpg
baseurl: '/2018'
